import localFont from "next/font/local";
import "./globals.css";
import { LanguageProvider } from "@/components/context/LanguageProvider";
import { getDictionary } from "@/lib/dictionaries/dictionaries";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Twitch",
  description: "Generated by create next app",
};

export default async function RootLayout({ children,params }) {
  const locale= ( await params).locale
  const dict= await getDictionary(locale)
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-w-[240px] max-w-[700px] m-auto h-screen ">
        <LanguageProvider dictionary={dict}>
        {children}
        </LanguageProvider>
        </div>
      </body>
    </html>
  );
}
